### ISSUE TITLE
[RAR5] No support for full encryption?

### ISSUE THREAD

**Issue by kyeastmood** [MacPaw/XADMaster#116]
Archive: [link](https://0x0.st/zCNv.rar)

When I try to list this archive with lsar, the message is:
````
archive.rar: RAR 5 (2 volumes)
Archive parsing failed! (Attempted to read more data than was available.)
````

There is no password prompt and this is a single-part archive.

Version: 1.10.1/Debian

Thanks

**Comment by PaulTaykalo** [comment]
Current version `lsar` asks for a password in for the provided archive.

```
~/Downloads/zCNv.rar: This archive requires a password to list.
Password (will not be shown):
RAR 5
```

As for (2 volumes) make sure that there are no archives around that can be potentially threated as multi-volume

Seems that this one should be fixed in here.
https://github.com/MacPaw/XADMaster/pull/87

**Comment by kyeastmood** [comment]
You are right. The original name of the archive was `rar5_encrypted.rar`. When I try to list it, there are no problems. However there was also another archive in the same directory, named `rar4_encrypted.rar`. And when these archives are together, my version of lsar treats them as a multipart archive.
 So this issue has been very likely already fixed and can be closed.
Thanks
