### ISSUE TITLE
The Unarchiver unzips to a damaged package but `unzip` works fine

### ISSUE THREAD

**Issue by jorijnsmit** [MacPaw/XADMaster#123]
To reproduce on macOS;

1. Download https://download.foldingathome.org/releases/public/release/fah-installer/osx-10.11-64bit/v7.5/fah-installer_7.5.1_x86_64.mpkg.zip
2. Open with The Unarchiver
3. Try to run resulting file
> “fah-installer_7.5.1_x86_64-1.mpkg” is damaged and can’t be opened. You should move it to the Bin.

Using `unzip` does result in a runnable file:
```shell
unzip fah-installer_7.5.1_x86_64.mpkg.zip 
Archive:  fah-installer_7.5.1_x86_64.mpkg.zip
 extracting: fah-installer_7.5.1_x86_64.pkg  
```
According to the App Store I am up to date with version 4.2.0.

**Comment by jorijnsmit** [comment]
Noticing now that there is a difference between the resulting extensions; The Unarchiver creates a `.mpkg` file whereas `unzip` produces a `.pkg` file.

**Comment by PaulTaykalo** [comment]
@jorijnsmit what verstion of the Unarchiver are you using?

**Comment by PaulTaykalo** [comment]
Oops. missed your comment. Give me a sec

**Comment by PaulTaykalo** [comment]
Works totally fine on the my machine (c) 
Please make sure that you don't have any other instances of The Unarchiver. 4.2.0 should work just fine

**Comment by PaulTaykalo** [comment]
![image](https://user-images.githubusercontent.com/119268/76779433-04c4c500-67b4-11ea-9967-247fed1fc4d7.png)

So the question is 
1) Have you double clicked on the file?
2) Where the downloaded file was located?
3) Do you have any specific options on where extracted files should be placed?

Thanks

**Comment by jorijnsmit** [comment]
Aha! So the bug lies in using the option "Create a new folder for the extracted files: `Always`".

This somehow renames the `.pkg` to `.mpkg`.

**Comment by PaulTaykalo** [comment]
Okay. it's not really an issue :) It's all about naming
When `fah-installer_7.5.1_x86_64.mpkg.zip` is extracted with "Create a new folder for the extracted files: `Always`". option enabled, then the next files will be created
```
fah-installer_7.5.1_x86_64.mpkg/fah-installer_7.5.1_x86_64.pkg
```
MacOS treats `fah-installer_7.5.1_x86_64.mpkg` directory as a valid `mpkg` package, but, obviously  it is not.

Not really a bug though :)
