### ISSUE TITLE
Xcode 10 issue: ld: library not found for -lstdc++

### ISSUE THREAD

**Issue by shazron** [MacPaw/XADMaster#84]
See https://stackoverflow.com/questions/51060596/ld-library-not-found-for-lstdc-6

Deprecation Notices:

> Building with libstdc++ was deprecated with Xcode 8 and is not supported in Xcode 10 when targeting iOS. C++ projects must now migrate to libc++ and are recommended to set a deployment target of iOS 7 or later. Besides changing the C++ Standard Library build setting, developers should audit hard-coded linker flags and target dependencies to remove references to libstdc++ (including -lstdc++, -lstdc++.6.0.9, libstdc++.6.0.9.tbd, and libstdc++.6.0.9.dylib). Project dependencies such as static archives that were built against libstdc++ will also need to be rebuilt against libc++. (40885260)

**Comment by PaulTaykalo** [comment]
@shazron we are aware of it. Currently, there is *Xcode10-Support*  branches in Universal Detector ad XADMaster. which you can use for building on Xcode 10.

We are about to switch master branch to Xcode 10 support while leaving *legacy* branch with older Xcode's.

So in order this to work, for now, just checkout *Xcode10-Support* in UniversalDetector and XADMaster reps.

**Comment by PaulTaykalo** [comment]
XADMaster as well as UnivesalDetector repositories were switched for the lastes Xcode Support.
Now, for xcode9 support, one can use *support/xcode9* branch
